version: '3.5'
services:
  redis:
    image: 'redis:alpine'
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - '6379:6379'
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

    networks:
      node_net:
        ipv4_address: 172.28.1.4

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672

  nats:
    image: nats:alpine
    ports:
      - '4222:4222'
    networks: ['nats']


networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  nats:
    name: nats
