version: '3.5'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      node_net:
        ipv4_address: 172.28.1.4

  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - 15672:15672
      - 5672:5672

  nats:
    image: nats:alpine
    ports:
      - '4222:4222'
    networks: ['nats']

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  nats:
    name: nats
